import {
  UserProfile,
  Account,
  Category,
  Transaction,
  Transfer,
  Budget,
  Loan,
  LoanPayment,
  RecurringTransaction,
  Plan,
  Subscription,
  PaymentSubmission,
  Banner,
  AuditLog,
} from '../types/database';

export const INITIAL_USER: UserProfile = {
  id: 'usr-1001-demo',
  email: 'demo@fintrack.app',
  full_name: 'Nowshad Hossain',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  currency: 'BDT',
  locale: 'en',
  theme: 'dark',
  role: 'ADMIN',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_PLANS: Plan[] = [
  {
    id: 'plan-free',
    name: 'Free Starter',
    slug: 'free',
    description: 'Essential personal budgeting for individuals starting their financial journey.',
    price: 0,
    billing_cycle: 'FREE',
    features: [
      'Up to 3 Accounts & Wallets',
      'Up to 5 Category Budgets',
      'Basic Income & Expense Tracking',
      '1 Month Historical Reports',
      'Single Currency (BDT)',
    ],
    limits: {
      max_accounts: 3,
      max_budgets: 5,
      export_reports: false,
      multi_currency: false,
      loans_enabled: true,
    },
    is_active: true,
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-pro-monthly',
    name: 'Pro Monthly',
    slug: 'pro-monthly',
    description: 'Advanced analytics, unlimited accounts, loans, and automated recurring rules.',
    price: 299,
    billing_cycle: 'MONTHLY',
    features: [
      'Unlimited Accounts & Wallets',
      'Unlimited Category Budgets',
      'Debt & Loan Manager with Repayments',
      'Automated Recurring Bills & Salary',
      'Advanced Analytics & CSV Export',
      'Multi-Currency (BDT, USD, EUR)',
      'Priority Support',
    ],
    limits: {
      max_accounts: 9999,
      max_budgets: 9999,
      export_reports: true,
      multi_currency: true,
      loans_enabled: true,
    },
    is_active: true,
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-pro-yearly',
    name: 'Pro Yearly',
    slug: 'pro-yearly',
    description: 'Best value for power users. Save 25% with annual billing + early feature access.',
    price: 2690,
    billing_cycle: 'YEARLY',
    features: [
      'All Pro Monthly Features',
      '2 Months Free Included',
      'Automated CSV Bank Importers',
      'Custom Categories & Badges',
      'Early Access to Beta Features',
      'VIP Concierge Support',
    ],
    limits: {
      max_accounts: 9999,
      max_budgets: 9999,
      export_reports: true,
      multi_currency: true,
      loans_enabled: true,
    },
    is_active: true,
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-lifetime',
    name: 'Lifetime Founder',
    slug: 'lifetime',
    description: 'One-time payment for lifetime access to all current and future FinTrack features.',
    price: 4999,
    billing_cycle: 'LIFETIME',
    features: [
      'Everything in Pro Yearly Forever',
      'Founder Badge on Profile',
      'No Recurring Subscriptions',
      'Direct Access to Developer Roadmap',
      'Unlimited Everything',
    ],
    limits: {
      max_accounts: 99999,
      max_budgets: 99999,
      export_reports: true,
      multi_currency: true,
      loans_enabled: true,
    },
    is_active: true,
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-1',
    user_id: 'usr-1001-demo',
    name: 'City Bank Savings',
    type: 'BANK',
    account_number: '•••• 4892',
    bank_name: 'City Bank PLC',
    balance: 145200,
    currency: 'BDT',
    color: '#3b82f6',
    icon: 'Building2',
    is_active: true,
    is_included_in_net_worth: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'acc-2',
    user_id: 'usr-1001-demo',
    name: 'bKash Wallet',
    type: 'MOBILE_BANKING',
    account_number: '01712-XXXXXX',
    balance: 24500,
    currency: 'BDT',
    color: '#ec4899',
    icon: 'Smartphone',
    is_active: true,
    is_included_in_net_worth: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'acc-3',
    user_id: 'usr-1001-demo',
    name: 'Cash in Hand',
    type: 'CASH',
    balance: 12800,
    currency: 'BDT',
    color: '#10b981',
    icon: 'Wallet',
    is_active: true,
    is_included_in_net_worth: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'acc-4',
    user_id: 'usr-1001-demo',
    name: 'BRAC Bank Credit Card',
    type: 'CREDIT_CARD',
    account_number: '•••• 1044',
    balance: -18400,
    currency: 'BDT',
    color: '#f43f5e',
    icon: 'CreditCard',
    is_active: true,
    is_included_in_net_worth: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // Income
  { id: 'cat-inc-1', name: 'Salary & Earnings', type: 'INCOME', color: '#10b981', icon: 'Briefcase', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-inc-2', name: 'Freelance & Contract', type: 'INCOME', color: '#059669', icon: 'Laptop', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-inc-3', name: 'Investments & Profit', type: 'INCOME', color: '#3b82f6', icon: 'TrendingUp', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // Expenses
  { id: 'cat-exp-1', name: 'Food & Dining', type: 'EXPENSE', color: '#f97316', icon: 'Utensils', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-exp-2', name: 'Groceries & Market', type: 'EXPENSE', color: '#84cc16', icon: 'ShoppingCart', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-exp-3', name: 'Housing & Rent', type: 'EXPENSE', color: '#6366f1', icon: 'Home', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-exp-4', name: 'Utilities & Bills', type: 'EXPENSE', color: '#eab308', icon: 'Zap', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-exp-5', name: 'Transportation & Fuel', type: 'EXPENSE', color: '#06b6d4', icon: 'Car', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-exp-6', name: 'Shopping & Apparel', type: 'EXPENSE', color: '#a855f7', icon: 'ShoppingBag', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-exp-7', name: 'Entertainment & Leisure', type: 'EXPENSE', color: '#ec4899', icon: 'Film', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-exp-8', name: 'Healthcare & Medical', type: 'EXPENSE', color: '#ef4444', icon: 'HeartPulse', is_system: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    user_id: 'usr-1001-demo',
    account_id: 'acc-1',
    category_id: 'cat-inc-1',
    type: 'INCOME',
    amount: 125000,
    description: 'Monthly Tech Lead Salary',
    transaction_date: new Date(Date.now() - 2 * 86400000).toISOString(),
    is_recurring: true,
    tags: ['salary', 'techcorp'],
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx-2',
    user_id: 'usr-1001-demo',
    account_id: 'acc-1',
    category_id: 'cat-exp-3',
    type: 'EXPENSE',
    amount: 35000,
    description: 'Apartment Monthly Rent',
    transaction_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    is_recurring: true,
    tags: ['rent', 'home'],
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx-3',
    user_id: 'usr-1001-demo',
    account_id: 'acc-2',
    category_id: 'cat-exp-2',
    type: 'EXPENSE',
    amount: 6850,
    description: 'Weekly Groceries at Shwapno',
    transaction_date: new Date(Date.now() - 4 * 86400000).toISOString(),
    is_recurring: false,
    tags: ['groceries', 'shwapno'],
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx-4',
    user_id: 'usr-1001-demo',
    account_id: 'acc-2',
    category_id: 'cat-exp-1',
    type: 'EXPENSE',
    amount: 2400,
    description: 'Dinner with Family at Gloria Jean\'s',
    transaction_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    is_recurring: false,
    tags: ['dining', 'weekend'],
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx-5',
    user_id: 'usr-1001-demo',
    account_id: 'acc-2',
    category_id: 'cat-exp-4',
    type: 'EXPENSE',
    amount: 3200,
    description: 'Electricity & High Speed Fiber Bill',
    transaction_date: new Date(Date.now() - 6 * 86400000).toISOString(),
    is_recurring: true,
    tags: ['utility', 'internet'],
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx-6',
    user_id: 'usr-1001-demo',
    account_id: 'acc-1',
    category_id: 'cat-inc-2',
    type: 'INCOME',
    amount: 42000,
    description: 'UI/UX Design Consultation Project',
    transaction_date: new Date(Date.now() - 8 * 86400000).toISOString(),
    is_recurring: false,
    tags: ['freelance', 'consulting'],
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'bg-1',
    user_id: 'usr-1001-demo',
    category_id: 'cat-exp-1',
    amount: 15000,
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
    alert_threshold: 80,
    notify_on_exceed: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'bg-2',
    user_id: 'usr-1001-demo',
    category_id: 'cat-exp-2',
    amount: 25000,
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
    alert_threshold: 80,
    notify_on_exceed: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'bg-3',
    user_id: 'usr-1001-demo',
    category_id: 'cat-exp-5',
    amount: 10000,
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
    alert_threshold: 80,
    notify_on_exceed: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_LOANS: Loan[] = [
  {
    id: 'loan-1',
    user_id: 'usr-1001-demo',
    person_name: 'Tanvir Ahmed',
    person_phone: '01819-123456',
    person_email: 'tanvir@gmail.com',
    type: 'LENT',
    principal_amount: 30000,
    interest_rate: 0,
    total_paid: 10000,
    due_date: new Date(Date.now() + 20 * 86400000).toISOString(),
    notes: 'Emergency medical loan to friend',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'loan-2',
    user_id: 'usr-1001-demo',
    person_name: 'Uncle Rafiq',
    person_phone: '01711-987654',
    type: 'BORROWED',
    principal_amount: 50000,
    interest_rate: 0,
    total_paid: 25000,
    due_date: new Date(Date.now() + 45 * 86400000).toISOString(),
    notes: 'Down payment assistance for vehicle',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_RECURRING: RecurringTransaction[] = [
  {
    id: 'rec-1',
    user_id: 'usr-1001-demo',
    account_id: 'acc-1',
    category_id: 'cat-inc-1',
    type: 'INCOME',
    amount: 125000,
    description: 'TechCorp Monthly Salary',
    frequency: 'MONTHLY',
    interval: 1,
    start_date: new Date(Date.now() - 60 * 86400000).toISOString(),
    next_run_date: new Date(Date.now() + 25 * 86400000).toISOString(),
    is_active: true,
    auto_create: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rec-2',
    user_id: 'usr-1001-demo',
    account_id: 'acc-1',
    category_id: 'cat-exp-3',
    type: 'EXPENSE',
    amount: 35000,
    description: 'Apartment Rent',
    frequency: 'MONTHLY',
    interval: 1,
    start_date: new Date(Date.now() - 60 * 86400000).toISOString(),
    next_run_date: new Date(Date.now() + 27 * 86400000).toISOString(),
    is_active: true,
    auto_create: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'bnr-1',
    title: '⚡ Upgrade to Pro & Unlock Unlimited Budgets',
    description: 'Get advanced debt ledgers, recurring bill automations, and CSV exports with 25% off annual billing.',
    link_url: '/settings',
    button_text: 'View Pro Features',
    type: 'UPGRADE',
    position: 'DASHBOARD',
    target_audience: 'ALL',
    priority: 10,
    is_active: true,
    background_color: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)',
    text_color: '#ffffff',
    badge_text: 'Limited 25% Off',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    impression_count: 1420,
    click_count: 384,
  },
  {
    id: 'bnr-2',
    title: '✨ New: Automated Debt & Loan Repayment Tracker',
    description: 'Easily track money lent to friends or borrowed funds with instant calculation of outstanding balances.',
    link_url: '/loans',
    button_text: 'Try Loans Now',
    type: 'FEATURE',
    position: 'DASHBOARD',
    target_audience: 'ALL',
    priority: 8,
    is_active: true,
    background_color: 'linear-gradient(135deg, #064e3b 0%, #065f46 50%, #047857 100%)',
    text_color: '#ffffff',
    badge_text: 'New Module',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    impression_count: 890,
    click_count: 215,
  },
  {
    id: 'bnr-3',
    title: '💳 Seamless bKash & Nagad Account Management',
    description: 'Monitor daily MFS limits and categorize every send-money / payment transaction with one tap.',
    link_url: '/accounts',
    button_text: 'Manage Wallets',
    type: 'ANNOUNCEMENT',
    position: 'TRANSACTIONS',
    target_audience: 'ALL',
    priority: 5,
    is_active: true,
    background_color: 'linear-gradient(135deg, #701a75 0%, #86198f 50%, #a21caf 100%)',
    text_color: '#ffffff',
    badge_text: 'Pro Tip',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    impression_count: 512,
    click_count: 120,
  },
];

export const INITIAL_PAYMENTS: PaymentSubmission[] = [
  {
    id: 'pay-101',
    user_id: 'usr-1001-demo',
    plan_id: 'plan-pro-yearly',
    amount: 2690,
    currency: 'BDT',
    payment_method: 'BKASH',
    transaction_id: 'BLA892X019',
    sender_number: '01711223344',
    status: 'APPROVED',
    admin_notes: 'Verified via bKash Merchant Portal',
    reviewed_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pay-102',
    user_id: 'usr-1001-demo',
    plan_id: 'plan-pro-monthly',
    amount: 299,
    currency: 'BDT',
    payment_method: 'BKASH',
    transaction_id: 'BKA993M812',
    sender_number: '01899887766',
    status: 'PENDING',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    user_id: 'usr-1001-demo',
    action: 'USER_LOGIN',
    entity_type: 'AUTH',
    details: { ip: '103.145.78.12', client: 'Chrome / Windows 11' },
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'aud-2',
    user_id: 'usr-1001-demo',
    action: 'CREATE_TRANSACTION',
    entity_type: 'TRANSACTION',
    entity_id: 'tx-1',
    details: { amount: 125000, type: 'INCOME', account: 'City Bank Savings' },
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'aud-3',
    user_id: 'usr-1001-demo',
    action: 'PAYMENT_SUBMITTED',
    entity_type: 'PAYMENT',
    entity_id: 'pay-102',
    details: { method: 'BKASH', amount: 299, trxId: 'BKA993M812' },
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
];
